import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import Nav from '@/components/Nav';
import Session from '@/providers/Session';
import UseQuery from '@/providers/UseQueryProvider';
import 'react-toastify/dist/ReactToastify.css';
import { Toast } from '@/hooks/use-toast';
import { Suspense } from 'react';
import LoadingComponent from '@/components/ui/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '🍏 Jobs for Developer | Jobs Dev ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={cn(`antialiased`, inter.className)}>
      <body
        suppressHydrationWarning={true}
        className='min-h-screen antialiased'
      >
        <Suspense>
          <UseQuery>
            <Session>
              <Nav />
              <div className='ml-[244px] max-lg:mx-auto h-full pt-2 relative'>
                <div className='container mx-auto px-5 max-lg:mt-24 max-lg:mb-24'>
                  {children}
                </div>
                <LoadingComponent size='lg' />
              </div>
            </Session>
          </UseQuery>
          <Toast />
        </Suspense>
      </body>
    </html>
  );
}
